#!/usr/bin/env bash
#
# defaults.sh (ds)
# version 2021.04.09
#
# AGPLv3 License
# Created by github.com/aerobounce on 2019/2/1.
# Copyright © 2019-present aerobounce. All rights reserved.
#
set -Cu

# Parser
# $1: Domain name.
# $2: -currentHost. Can be empty.
parse() {
    # Defaults Key and Value.
    local KEY=""
    local VALUE=""

    # Begin writing script.
    # Declare shebang.
    printf '#!/usr/bin/env bash\n\n'

    # Parse XML line by line.
    # shellcheck disable=SC2086
    defaults ${2:-} export "$1" - | while IFS= read -r; do

        # Value type.
        local VALUE_TYPE="${REPLY#*</}"
        VALUE_TYPE="${VALUE_TYPE%>}"

        case "$REPLY" in
            $'\t'"<key>"*)
                # Extract KEY
                KEY="${REPLY#$'\t'<key>}"
                KEY=\""${KEY%</key>}"\"
                ;;

            $'\t'"<string>"* | $'\t'"<date>"*)
                # Extract Value (String or Date)
                VALUE="${REPLY/$'\t'<$VALUE_TYPE>/}"
                VALUE="-$VALUE_TYPE '${VALUE/<\/$VALUE_TYPE>/}'"
                ;;

            $'\t'"<integer>"*)
                # Extract Value (Integer)
                VALUE="${REPLY/$'\t'<$VALUE_TYPE>/}"
                VALUE="-$VALUE_TYPE ${VALUE/<\/$VALUE_TYPE>/}"
                ;;

            $'\t'"<real>"*)
                # Extract Value (Float)
                VALUE="${REPLY/$'\t'<$VALUE_TYPE>/}"
                VALUE="-float ${VALUE/<\/$VALUE_TYPE>/}"
                ;;

            $'\t'"<true/>" | $'\t'"<false/>")
                # Extract Value (Boolean)
                VALUE="${REPLY/$'\t'</}"
                VALUE="-boolean ${VALUE/\/>/}"
                ;;

            $'\t'"<dict/>" | $'\t'"<array/>")
                # Extract Value (Empty Array or Dict)
                VALUE="'${REPLY#$'\t'}'"
                ;;

            $'\t'"<data>" | $'\t'"<array>" | $'\t'"<dict>")
                # 1. Data, Array or Dict: Tag Begins
                if [[ -n ${2:-} ]]; then
                    echo "defaults ${2:-} write $1 $KEY '"$'\n'"${REPLY#$'\t'}"
                else
                    echo "defaults write $1 $KEY '"$'\n'"${REPLY#$'\t'}"
                fi

                KEY=""
                VALUE=""

                continue
                ;;

            $'\t'"</data>" | $'\t'"</array>" | $'\t'"</dict>")
                # 3. Data, Array or Dict: Tag Ends
                echo "${REPLY#$'\t'}"$'\n'\'

                KEY=""
                VALUE=""

                continue
                ;;

            *)
                # 2. Data, Array or Dict: Raw XML

                # Skip XML Declaration, Plist info and Root Tags
                local DOCTYPE='<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
                DOCTYPE+='"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
                [[ $REPLY == '<?xml version="1.0" encoding="UTF-8"?>' ]] && continue
                [[ $REPLY == "$DOCTYPE" ]] && continue
                [[ $REPLY == '<plist version="1.0">' ]] && continue
                [[ $REPLY == "<dict>" ]] && continue
                [[ $REPLY == "</dict>" ]] && continue
                [[ $REPLY == "</plist>" ]] && continue

                # Empty case.
                [[ $REPLY == "<dict/>" ]] && echo "# Empty plist." && continue

                REPLY=${REPLY#$'\t'}
                REPLY=${REPLY//\'/\'\"\'\"\'} # Escape single quote
                echo "$REPLY"
                ;;

        esac

        # If KEY and VALUE are ready, echo result
        [[ -n $KEY && -n $VALUE ]] || continue

        if [[ -n ${2:-} ]]; then
            echo "defaults ${2:-} write $1 $KEY $VALUE"
        else
            echo "defaults write $1 $KEY $VALUE"
        fi

        KEY=""
        VALUE=""
    done
}

save() {
    (
        local IFS=', '
        local DOMAIN

        # Current Host Domains
        for DOMAIN in $(defaults -currentHost domains) NSGlobalDomain; do
            {
                echo "currentHost" "$DOMAIN"
                parse "$DOMAIN" -currentHost >> "$SAVE_DIR/$DOMAIN.currentHost.sh"
                chmod a+x "$SAVE_DIR/$DOMAIN.currentHost.sh"
            } &
            while [[ $(jobs -p | wc -w) -ge 8 ]]; do sleep 0.1; done
        done
        wait

        # User Domains + NSGlobalDomain
        for DOMAIN in $(defaults domains) NSGlobalDomain; do
            {
                echo "$DOMAIN"
                parse "$DOMAIN" >> "$SAVE_DIR/$DOMAIN.sh"
                chmod a+x "$SAVE_DIR/$DOMAIN.sh"
            } &
            while [[ $(jobs -p | wc -w) -ge 8 ]]; do sleep 0.1; done
        done
        wait
    )
}

usage() {
    local y='\e[1;33m' # Yellow and Bold
    local p='\e[1;35m' # Purple and Bold
    local c='\e[4;36m' # Cyan and Underlined
    local g='\e[0;32m' # Green
    local r='\e[0m'    # Reset

    # shellcheck disable=SC2059
    printf "${p}NAME${r}
    ${y}defaults.sh${r} -- Convert user defaults (plist) into shell script

${p}USAGE${r}
    ${y}ds${r}
    ${y}ds${r} (-d | domain) ${c}<(domain | plist-path)>${r}
    ${y}ds${r} (-c | currentHost) ${c}<domain>${r}
    ${y}ds${r} (-s | save)

${p}DESCRIPTION${r}
    ${y}[no command]${r}
            Shows this help.

    ${y}(-d | domain)${r} ${c}<(domain | plist-path)>${r}
            Prints parsed user defaults of specified domain or .plist file.
            Both of the following commands are valid:
                ${g}$ ds -d com.apple.dock${r}
                ${g}$ ds -d ~/Library/Preferences/com.apple.dock.plist${r}

    ${y}(-c | currentHost)${r} ${c}<domain>${r}
            Same as ${y}(-d | domain)${r}, except operation will be restricted
            to the host the user is currently logged in on.

    ${y}(-s | save)${r}
            Exports all the defaults to ~/Desktop as executable .sh files.
            Domains are:
                'defaults -currentHost domains' + NSGlobalDomain
                'defaults domains' + NSGlobalDomain
"
    exit 0
}

fatalError() {
    echo "$1" 1>&2
    exit 1
}

# Early Exit
[[ $# -eq 0 ]] && usage

# Main
for arg in "$@"; do
    case "$arg" in
        currentHost | -c)
            shift
            [[ ! $# -eq 1 ]] && fatalError "Invalid number of arguments."
            parse "$1" -currentHost
            ;;

        domain | -d)
            shift
            [[ ! $# -eq 1 ]] && fatalError "Invalid number of arguments."
            parse "$1"
            ;;

        save | -s)
            shift
            [[ ! $# -eq 0 ]] && fatalError "Invalid number of arguments."

            SAVE_DIR="$HOME/Desktop/ds $(date "+%Y.%m.%d %H.%M.%S")"
            [[ ! -e $SAVE_DIR ]] && mkdir "$SAVE_DIR"
            save
            ;;

        *)
            fatalError "Invalid arguments."
            usage
            ;;

    esac
    exit $?
done

# Fallback
usage
